name: FeedCommand
version: 1.1
main: fr.thorite.feedcommand.FeedCommand
author: Thorite
description: Feed !
 
commands:
    feed:
        usage: /<command>
        aliases: [food, sate]
        description: Feed.